# Generated by Django 3.0.2 on 2020-01-25 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0002_product_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
