# Generated by Django 3.0.2 on 2020-03-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('techId', models.AutoField(primary_key=True, serialize=False)),
                ('techName', models.CharField(max_length=100)),
                ('techStrength', models.IntegerField()),
            ],
        ),
    ]
